runtime: nodejs20
service: api
env: standard

entrypoint: node dist/app.js

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"
  CORS_ORIGIN: "https://frontend-dot-gen-lang-client-0403310649.uc.r.appspot.com"
  API_KEY: "AIzaSyDBiofolWvdcaPIC_c3uvGVfsgCk3Xa3NM"
  MONGODB_URI: "mongodb+srv://akshayvijaynair:1hPtamNfWbSl6058@cluster0.o879l.mongodb.net/quizApp?retryWrites=true&w=majority"
  DB_NAME: "quizApp"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Configure logging
runtime_config:
  operating_system: "ubuntu22"
  enable_stackdriver_integration: true
