runtime: nodejs20
service: api
env: standard

entrypoint: node dist/app.js

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  include:
    - env_variables.yaml

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Configure logging
runtime_config:
  operating_system: "ubuntu22"
  enable_stackdriver_integration: true
